@echo off
echo 🚀 Starting SocioHiro deployment...

echo 📦 Installing dependencies...
call npm run install:all

echo 🔨 Building frontend...
call npm run build:full

echo 🌐 Starting server...
cd backend
call npm start 